<?php
return array(
  'facciones'=>[
    '1' => 'NEUTRAL',
    '2' => 'REINOS DEL NORTE',
    '3' => 'SCOIATAEL',
    '4' => 'MOUNSTROS',
    '5' => 'SKELLIGE',
    ],
    'tipo'=>[
      '1' => 'ESPECIAL',
      '2' => 'LÍDER',
      '3' => 'TROPA',
      '4' => 'PERSONAJE',
      '5' => 'HEROE',
      '6' => 'LEAL',
      '7' => 'DESLEAL',
      ],
      'fila'=>[
        '1' => 'CUERPO A CUERPO',
        '2' => 'ARQUEROS',
        '3' => 'CATAPULTAS',
        ],
        'rareza'=>[
          '1' => 'COMÚN',
          '2' => 'POCO COMÚN',
          '3' => 'ÉPICO',
          '4' => 'LEGENDARIO',
          ],
          'habilidad'=>[
            '1' => 'INSPIRACIÓN',
            '2' => 'INTERCAMBIO',
            '3' => 'LEGIÓN QUE CAMINA ENTRE LA NIEBLA',
            '4' => 'ESPIAR',
            '5' => 'ESCARCHA',
            '6' => 'REUNIR',
            '7' => 'ALENTAR',
            '8' => 'CONVOCAR',
            '9' => 'FIEL SIRVIENTE',
            '10' => 'HORDA',
            '11' => 'RESURRECCIÓN',
            '12' => 'RETIRADA',
            '13' => 'AUTORIZAR',
            '14' => 'BUEN TIEMPO',
            '15' => 'CHAMÁN',
            '16' => 'EMBOSCADA',
            '17' => 'PLAGA',
            '18' => 'LIMITAR TIEMPO',
            '19' => 'COMANDANTE DEL NORTE',
            '20' => 'IGNICIÓN',
            '21' => 'DESEO DE MUERTE',
            '22' => 'PRESAGIO HELADO',
            '23' => 'NIEBLA',
            '24' => 'RESISTENCIA',
            '25' => 'ESPORA',
            '26' => 'INCINERAR',
            '27' => 'AHÍ ESTARÉ PARA TÍ',
            '28' => 'ELECCIÓN',
            '29' => 'LLUVIA',
            '30' => 'DESALENTAR',
            '31' => 'LEGIÓN CAMINANTE HELADA',
            ]
  );
